# Generated by Django 2.2.4 on 2019-12-17 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mug',
            name='category',
            field=models.CharField(choices=[('CREAMIC', 'CREAMIC'), ('GLASS', 'GLASS'), ('STAINLESS', 'STAINLESS'), ('MELAMINE ', 'MELAMINE'), ('CHINA ', 'CHINA')], max_length=100),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSTAFF', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
