# Generated by Django 2.2.4 on 2019-12-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191217_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='mug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='mug',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
